import React from 'react';

import "./fizzbuzz-styles.scss";

class FizzBuzz extends React.Component{
    constructor(){
        super();

        this.state = {
            array: [],
            originalArray: [],
            color : "rebeccapurple",
            visible : false
        }
    }

    

    fizzBuzz(array){
        this.setState({array:[], visible:true});
        const newArray = [];
        for(let number = 0; number < 24; number++){
            if(array[number]%3 === 0 && array[number]%5 === 0){
                newArray[number] = "FizzBuzz";
            }
            else if(array[number]%3 === 0){
                newArray[number] = "Fizz";
            }
            else if(array[number]%5 === 0){
                newArray[number] = "Buzz";
            }
            else{
                newArray[number] = "" + array[number];
            }
            this.getAnimationsForNumbers(newArray);
        }
    }

    componentDidMount(){
        window.scrollTo(0,0);
        this.getNumbersForArray();
    }

    getNumbersForArray(){
        const array = [];
        for(let i=0; i< 24; i++){
            array.push(Math.floor(Math.random()*100));
        }
        this.setState({array:array,originalArray:array});
        
    }

    getAnimationsForNumbers(array){
        const tempArray = [];
        for(let i=0;i<array.length;i++){
            setTimeout(() => {
                tempArray.push(array[i]);
                this.setState({array:tempArray});
                if(i === array.length-1){
                    this.setState({visible:false});
                }
            },
            i*1000);
            
        }
        
    }

    revertToOriginalArray(){
        this.setState({array:this.state.originalArray});
    }
    

    render(){
        const {array} = this.state;
        

        return(
            <>
            
            <div className = "container">
                <div className = "problem"> FizzBuzz </div> 
                <div className = "problemStatement">
                    
                    
                 Given a list of numbers, you have to insert the value "Fizz" for numbers divisible by 3,
                 "Buzz" for numbers divisible by 5 and "FizzBuzz" for numbers divisible by both 3 and 5.
                 Given a list of random numbers generated by click on the "Get numbers for Array" button,
                 you can generate the respective FizzBuzz values by clicking on the "Generate Fizz Buzz
                 Algorithm" button.   
                </div>
                {array.map((value,index) => (
                    
                <div key = {index} className = "numbers" >
                    {value}
                </div>
            ))}
                
            <div className = {!this.state.visible?"":"fizzbuzzButtonSpace"}>
            {!this.state.visible ?<button onClick = {() => {this.getNumbersForArray()}} className = "buttonClick" > Get numbers for Array 
            </button> : null}
            
            {!this.state.visible ? <button onClick = {() => {this.fizzBuzz(array)}} className = "buttonClick">Generate Fizz Buzz Algorithm </button>
            : null}

            {!this.state.visible ? <button onClick = {() => {this.revertToOriginalArray()}} className = "buttonClick"> Revert to Original Array </button> : null}
            </div>
            
            </div>
            </>
        );
    }
}

export default FizzBuzz;