import React from 'react';

import "./fizzbuzz-styles.scss";

class FizzBuzz extends React.Component{
    constructor(){
        super();

        this.state = {
            array: [],
            color : "rebeccapurple",
        }
    }

    

    fizzBuzz(array){
        for(let number = 0; number < 24; number++){
            if(array[number]%3 === 0 && array[number]%5 === 0){
                array[number] = "FizzBuzz";
            }
            else if(array[number]%3 === 0){
                array[number] = "Fizz";
            }
            else if(array[number]%5 === 0){
                array[number] = "Buzz";
            }
            else{
                array[number] = "" + array[number];
            }
            
            

            setTimeout(
                function() {
                    this.setState({array,color:"black"});
                }
                .bind(this),
                1000
            );
        }
    }

    componentDidMount(){
        this.getNumbersForArray();
    }

    getNumbersForArray(){
        const array = [];
        for(let i=0; i< 24; i++){
            array.push(Math.floor(Math.random()*100));
        }
        this.setState({array, color:"rebeccapurple",animation:"changeColor"});
    }
    

    render(){
        const {array} = this.state;
        return(
            <>
            
            <div className = "container">
                <div className = "problem"> FizzBuzz </div> 
                <div className = "problemStatement">
                    
                    <br />
                 Given a list of numbers, you have to insert the value "Fizz" for numbers divisible by 3,
                 "Buzz" for numbers divisible by 5 and "FizzBuzz" for numbers divisible by both 3 and 5.
                 Given a list of random numbers generated by click on the "Get numbers for Array" button,
                 you can generate the respective FizzBuzz values by clicking on the "Generate Fizz Buzz
                 Algorithm" button.   
                </div>
                {array.map((value,index) => (
                    
                <div key = {index} className = "numbers" style ={
                    {
                        
                    //animation: this.state.animation,
                    //color: this.state.color
                }}>
                    {value}
                    

                </div>
                
            ))}
                
            <button onClick = {() => {this.getNumbersForArray()}} className = "buttonClick" > Get numbers for Array 
            </button>
            
            <button onClick = {() => {this.fizzBuzz(array)}} className = "buttonClick">Generate Fizz Buzz Algorithm </button>
            
            
            </div>
            </>
        );
    }
}

export default FizzBuzz;